name: Expense Tracker DApp deploy to surge

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Node JS
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          version: 12 

      # Installs dependencies
      - name: Installs all dependencies
        run: npm install

      # Installs Surge
      - name: Install surge
        run: npm install -g surge

      # Deploys to Surge
      - name: Deploy to surge
        run: surge ./ ethereum-expense-tracker.surge.sh --token ${{secrets.SURGE_TOKEN}}
